CREATE TABLE PERSONAS 
("ID" NUMBER(*,0) NOT NULL, 
"NOMBRE" VARCHAR2(55), 
"CORREO" VARCHAR2(55), 
"TELEFONO" VARCHAR2(10)
);

INSERT INTO personas (ID, NOMBRE, CORREO, TELEFONO) 
VALUES (1, 'Akin','akin.ramirez@hotmail.com','99999999');

SELECT * FROM personas;
